#! /bin/bash
[ -d out ] && rm -fr out

ARGS="desktop:run $@"

function gradlew_do()
{
    echo "./gradlew $ARGS" && ./gradlew $ARGS
}

case "$1" in
    "c")
        ARGS="clean packs $ARGS $@"
        gradlew_do
        ;;
    "a")
        ARGS="android:installDebug android:run $@"
        gradlew_do
        echo "on failure: sudo adb kill-server; (sudo adb start-server;) sudo adb devices"
        ;;
    "t")
        ARGS="core:test $@"
        gradlew_do
        ;;
    "j")
        ARGS="core:compileJava $@"
        gradlew_do
        ;;
    "d")
        ARGS="desktop:dist $@"
        gradlew_do
        mv ./desktop/build/libs/desktop-1.0.jar TankOnTank.jar
        ;;
    *)
        gradlew_do
        ;;
esac

