#! /bin/bash
[ -d out ] && rm -fr out

ARGS="desktop:run"

case "$1" in
    "c")
        ARGS="clean packs $ARGS"
        shift
        ;;
    "a")
        ARGS="android:installDebug android:run"
        shift
        ;;
    "t")
        ARGS="core:test"
        shift
        ;;
    "j")
        ARGS="core:compileJava"
        shift
        ;;
esac

echo "./gradlew $ARGS $@" && ./gradlew $ARGS $@
