#! /bin/bash
[ -d out ] && rm -fr out

ARGS="desktop:run"

case "$1" in
    "c")
        ARGS="clean packs $ARGS"
        ;;
    "a")
        ARGS="android:installDebug android:run"
        ;;
    "t")
        ARGS="core:test"
        ;;
esac

echo "./gradlew $ARGS" && ./gradlew $ARGS
