#! /bin/bash

PKG=ch.asynk.rustanddust.android

for I in cache databases files lib; do
    echo " *** $I"
    adb shell run-as $PKG ls /data/data/$PKG/$I
    echo
done

adb shell run-as $PKG "cat /data/data/$PKG/databases/rustanddust.sqlite > '/sdcard/db.sqlite'"
adb pull '/sdcard/db.sqlite'
adb shell "rm '/sdcard/db.sqlite'"

echo " *** SCHEMA ***"
sqlite3 db.sqlite '.schema'
echo
echo " *** CONFIG ***"
sqlite3 db.sqlite 'select * from config;'
echo
echo " *** PLAYERS ***"
sqlite3 db.sqlite 'select * from players;'
echo
echo " *** BATTLES ***"
sqlite3 db.sqlite 'select * from battles;'
echo
echo " *** GAMES ***"
sqlite3 db.sqlite 'select * from games;'
echo
echo " *** TURNS ***"
sqlite3 db.sqlite 'select * from turns;'
echo
