#! /bin/bash

sqlite3  android/assets/data/rustanddust.sqlite 'select state from games order by ts desc limit 1' > state.json
sqlite3  android/assets/data/rustanddust.sqlite 'select orders from games order by ts desc limit 1' > orders.json
# echo "[" > turns.json
# sqlite3  android/assets/data/rustanddust.sqlite 'select payload from turns where game=(select _id from games order by ts desc limit 1) order by _id' | while read rec; do echo "$rec,"; done >> turns.json
# sed -i '$s/,$/]/' turns.json
